version: '3.8'

services:
  node_backend:
    container_name: node_docker
    image: mazufik/node_docker:1.1.0
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      - EXTERNAL_PORT=3001
      - PGDATABASE=nodedocker_db
      - PGUSER=postgres
      - PGPASSWORD=secret
      - PGHOST=node_db
    depends_on:
      - node_db
  node_db:
    container_name: node_db
    image: 'postgres:14-alpine'
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=nodedocker_db
    volumes:
      - nps_data:/var/lib/postgresql/data

volumes:
  nps_data: {}
